### ISSUE TITLE
'terminate_on_signal' segfaulting

### ISSUE THREAD

**Issue by eduda** [jib/ipc-cmd#15]
Here’s a test case:

[root@host~]# perl testme2 &
[1] 3931
[root@host~]# start

RSS is always increasing.
[root@host~]# while true; do ps -aux | grep 3931 | grep -v grep; sleep 2; done
root      3931 19.6  0.0 158872 11220 pts/0    S    17:01   0:02 perl testme2
root      3931 18.6  0.0 159136 11488 pts/0    R    17:01   0:02 perl testme2
root      3931 17.7  0.0 159400 11736 pts/0    R    17:01   0:03 perl testme2
root      3931 17.0  0.0 159532 11960 pts/0    S    17:01   0:03 perl testme2
root      3931 16.4  0.0 159788 12184 pts/0    S    17:01   0:03 perl testme2
root      3931 15.8  0.0 160048 12376 pts/0    S    17:01   0:03 perl testme2
root      3931 15.3  0.0 160176 12568 pts/0    R    17:01   0:03 perl testme2
root      3931 14.8  0.0 160308 12744 pts/0    R    17:01   0:04 perl testme2
^C
[root@host~]# cat testme2
#!/usr/bin/perl -w

use IPC::Cmd qw[can_run run run_forked];

my $args = { 'terminate_on_signal' => "INT" };

print "start\n";

for my $i ( 1..2000000000 ) {
        run_forked('/bin/cat /etc/hosts',$args);
}

print "end\n";

might be a circular ref issue in install_layered_signal with previous_handler on %SIG

**Comment by kohts** [comment]
Fix: https://github.com/jib/ipc-cmd/pull/16

Thanks for error report!
